teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 7
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5
    scale_linear_autorun:
      x: 1.0

    axis_angular:
      yaw: 6
    axis_angular_adjustment:
      yaw: 3
    scale_angular:
      yaw: 0.4

    enable_button: 2  # L2 shoulder button
    enable_turbo_button: 0  # L1 shoulder button
    enable_autorun_button: 1
